name: Monitor MOSiR (Selenium)

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Google Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb

    - name: Install Python dependencies
      run: |
        pip install selenium beautifulsoup4 webdriver-manager pytz

    - name: Run monitor script
      run: python monitor.py

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Aktualizacja danych: $(date)"
        file_pattern: |
          frekwencja.csv
          log.txt
