name: Monitor MOSiR (Ubuntu + Selenium)

on:
  schedule:
    - cron: '*/15 * * * *'  # co 15 minut
  workflow_dispatch:

jobs:
  run-monitor:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Chromium and ChromeDriver
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium beautifulsoup4

    - name: Run monitor script
      run: python monitor.py

    - name: Commit and push changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Aktualizacja danych: $(date)"
        file_pattern: frekwencja.csv
